-- =============================================================================
-- V1__create_schema.sql
-- Pulse Pass — esquema relacional inicial
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Tabla: venues
-- -----------------------------------------------------------------------------
CREATE TABLE venues (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code     VARCHAR(50)  NOT NULL UNIQUE,
    name     VARCHAR(150) NOT NULL,
    city     VARCHAR(100) NOT NULL,
    address  VARCHAR(150) NOT NULL,
    capacity BIGINT       NOT NULL,
    active   BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT chk_venue_capacity CHECK (capacity > 0)
);

-- -----------------------------------------------------------------------------
-- Tabla: events
-- -----------------------------------------------------------------------------
CREATE TABLE events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_code  VARCHAR(50)  NOT NULL UNIQUE,
    name        VARCHAR(150) NOT NULL,
    description VARCHAR(500) NOT NULL,
    category    VARCHAR(20)  NOT NULL,
    status      VARCHAR(20)  NOT NULL,
    event_date  DATE         NOT NULL,
    minimum_age INT,
    venue_id    BIGINT       NOT NULL,

    CONSTRAINT fk_event_venue
        FOREIGN KEY (venue_id) REFERENCES venues (id),

    CONSTRAINT chk_event_category
        CHECK (category IN (
            'MUSIC',
            'SPORTS',
            'TECHNOLOGY',
            'EDUCATION',
            'CULTURE',
            'ENTERTAINMENT'
        )),

    CONSTRAINT chk_event_status
        CHECK (status IN (
            'DRAFT',
            'PUBLISHED',
            'SOLD_OUT',
            'CANCELLED',
            'FINISHED'
        ))
);

-- -----------------------------------------------------------------------------
-- Tabla: artists
-- -----------------------------------------------------------------------------
CREATE TABLE artists (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stage_name VARCHAR(75)  NOT NULL UNIQUE,
    country    VARCHAR(100) NOT NULL,
    genre      VARCHAR(100) NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE
);

-- -----------------------------------------------------------------------------
-- Tabla asociativa: event_artists (relación N:M)
-- -----------------------------------------------------------------------------
CREATE TABLE event_artists (
    event_id  BIGINT NOT NULL,
    artist_id BIGINT NOT NULL,

    PRIMARY KEY (event_id, artist_id),

    CONSTRAINT fk_event_artists_event
        FOREIGN KEY (event_id) REFERENCES events (id),

    CONSTRAINT fk_event_artists_artist
        FOREIGN KEY (artist_id) REFERENCES artists (id)
);

-- -----------------------------------------------------------------------------
-- Tabla: users
-- -----------------------------------------------------------------------------
CREATE TABLE users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email    VARCHAR(150) NOT NULL UNIQUE,
    active   BOOLEAN      NOT NULL DEFAULT TRUE
);

-- -----------------------------------------------------------------------------
-- Tabla: user_profiles
-- -----------------------------------------------------------------------------
CREATE TABLE user_profiles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50)  NOT NULL,
    last_name  VARCHAR(50)  NOT NULL,
    phone      VARCHAR(30),
    city       VARCHAR(50),
    birth_date DATE,
    user_id    BIGINT       NOT NULL UNIQUE,

    CONSTRAINT fk_user_profile_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

-- -----------------------------------------------------------------------------
-- Tabla: tickets
-- -----------------------------------------------------------------------------
CREATE TABLE tickets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_code   VARCHAR(50)    NOT NULL UNIQUE,
    type          VARCHAR(20)    NOT NULL,
    price         DECIMAL(10, 2) NOT NULL,
    status        VARCHAR(20)    NOT NULL,
    purchase_date TIMESTAMP      NOT NULL,
    user_id       BIGINT         NOT NULL,
    event_id      BIGINT         NOT NULL,

    CONSTRAINT fk_ticket_user
        FOREIGN KEY (user_id) REFERENCES users (id),

    CONSTRAINT fk_ticket_event
        FOREIGN KEY (event_id) REFERENCES events (id),

    CONSTRAINT chk_ticket_type
        CHECK (type IN (
            'GENERAL',
            'VIP',
            'BACKSTAGE',
            'STUDENT'
        )),

    CONSTRAINT chk_ticket_status
        CHECK (status IN (
            'RESERVED',
            'PAID',
            'CANCELLED',
            'USED'
        )),

    CONSTRAINT chk_ticket_price
        CHECK (price >= 0)
);

-- =============================================================================
-- Índices para mejorar el rendimiento de las consultas
-- =============================================================================

CREATE INDEX idx_events_venue_id
    ON events (venue_id);

CREATE INDEX idx_events_status
    ON events (status);

CREATE INDEX idx_events_event_date
    ON events (event_date);

CREATE INDEX idx_tickets_user_id
    ON tickets (user_id);

CREATE INDEX idx_tickets_event_id
    ON tickets (event_id);

CREATE INDEX idx_tickets_status
    ON tickets (status);

CREATE INDEX idx_event_artists_artist_id
    ON event_artists (artist_id);
