-- =============================================================================
-- V1__create_schema.sql
-- Pulse Pass — esquema relacional inicial
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Tabla: venues
-- -----------------------------------------------------------------------------
CREATE TABLE venues (
                            id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            code    VARCHAR(50)  NOT NULL UNIQUE,
                            name    VARCHAR(150) NOT NULL,
                            city    VARCHAR(100) NOT NULL,
                            addrees VARCHAR(150) NOT NULL,
                            capacity BIGINT NOT NULL,
                            active active BOOLEAN NOT NULL,

                    CONSTRAINT chk_capacity CHECK (capacity > 0)
);

-- -----------------------------------------------------------------------------
-- Tabla: events
-- -----------------------------------------------------------------------------
CREATE TABLE animals (
                         id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         animal_code     VARCHAR(50)  NOT NULL UNIQUE,
                         common_name     VARCHAR(150) NOT NULL,
                         scientific_name VARCHAR(150),
                         sex             VARCHAR(10)  NOT NULL,
                         rescue_case_id  BIGINT       NOT NULL UNIQUE,

                         CONSTRAINT fk_animal_rescue_case
                             FOREIGN KEY (rescue_case_id) REFERENCES rescue_cases (id),

                         CONSTRAINT chk_animal_sex
                             CHECK (sex IN ('MALE', 'FEMALE', 'UNKNOWN'))
);

-- -----------------------------------------------------------------------------
-- Tabla: animals
-- -----------------------------------------------------------------------------
CREATE TABLE medical_records (
                                 id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 animal_id          BIGINT         NOT NULL UNIQUE,
                                 initial_weight     DECIMAL(7, 2),
                                 initial_condition  VARCHAR(100),
                                 injuries           TEXT,
                                 observations       TEXT,

                                 CONSTRAINT fk_medical_record_animal
                                     FOREIGN KEY (animal_id) REFERENCES animals (id)
);

-- -----------------------------------------------------------------------------
-- Tabla: medical_records
-- -----------------------------------------------------------------------------
CREATE TABLE events (
                        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        event_code      VARCHAR(50)  NOT NULL UNIQUE,
                        name            VARCHAR(50)  NOT NULL,
                        description     VARCHAR(200) NOT NULL,
                        category        VARCHAR (20) NOT NULL,
                        status          VARCHAR (20) NOT NULL,
                        event_date      DATE NOT NULL,
                        minimum_age     INT,
                        streaming_url   VARCHAR(500),
                        venue_id BIGINT NOT NULL,

                        CONSTRAINT fk_event_venue
                            FOREIGN KEY (venue_id) REFERENCES venues (id),

                        CONSTRAINT chk_event_category
                            CHECK (category IN (
                                                'MUSIC',
                                                'SPORTS',
                                                'TECHNOLOGY',
                                                'EDUCATION',
                                                'CULTURE',
                                                'ENTERTAINMENT'
                                ))
                        CONSTRAINT chk_event_status
                            CHECK (status IN(
                                'DRAFT',
                                'PUBLISHED',
                                'SOLD_OUT',
                                'CANCELLED',
                                'FINISHED'
                                ))
);

-- -----------------------------------------------------------------------------
-- Tabla: artists
-- -----------------------------------------------------------------------------
CREATE TABLE artists (
                             id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             stage_name      VARCHAR(75)  NOT NULL UNIQUE,
                             country         VARCHAR(100) NOT NULL,
                             genre           VARCHAR(100) NOT NULL,
                             active            BOOLEAN      NOT NULL DEFAULT TRUE
);

-- -----------------------------------------------------------------------------
-- Tabla: expertise
-- -----------------------------------------------------------------------------
CREATE TABLE expertise (
                           id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(100) NOT NULL UNIQUE
);

-- -----------------------------------------------------------------------------
-- Tabla asociativa: specialist_expertise  (relación N:M)
-- -----------------------------------------------------------------------------
CREATE TABLE specialist_expertise (
                                      specialist_id BIGINT NOT NULL,
                                      expertise_id  BIGINT NOT NULL,

                                      PRIMARY KEY (specialist_id, expertise_id),

                                      CONSTRAINT fk_specialist_expertise_specialist
                                          FOREIGN KEY (specialist_id) REFERENCES specialists (id),

                                      CONSTRAINT fk_specialist_expertise_expertise
                                          FOREIGN KEY (expertise_id) REFERENCES expertise (id)
);

-- -----------------------------------------------------------------------------
-- Tabla: treatments
-- -----------------------------------------------------------------------------
CREATE TABLE treatments (
                            id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            animal_id      BIGINT      NOT NULL,
                            specialist_id  BIGINT      NOT NULL,
                            performed_at   TIMESTAMP   NOT NULL,
                            type           VARCHAR(30) NOT NULL,
                            description    TEXT,

                            CONSTRAINT fk_treatment_animal
                                FOREIGN KEY (animal_id) REFERENCES animals (id),

                            CONSTRAINT fk_treatment_specialist
                                FOREIGN KEY (specialist_id) REFERENCES specialists (id),

                            CONSTRAINT chk_treatment_type
                                CHECK (type IN (
                                                'WOUND_CARE',
                                                'HYDRATION',
                                                'MEDICATION',
                                                'SURGERY',
                                                'NUTRITION',
                                                'PHYSIOTHERAPY',
                                                'OBSERVATION'
                                    ))
);

-- =============================================================================
-- Índices para mejorar el rendimiento de las consultas
-- =============================================================================

CREATE INDEX idx_rescue_cases_center_id
    ON rescue_cases (rescue_center_id);

CREATE INDEX idx_rescue_cases_status
    ON rescue_cases (status);

CREATE INDEX idx_rescue_cases_rescue_date
    ON rescue_cases (rescue_date);

CREATE INDEX idx_treatments_animal_id
    ON treatments (animal_id);

CREATE INDEX idx_treatments_specialist_id
    ON treatments (specialist_id);

CREATE INDEX idx_treatments_performed_at
    ON treatments (performed_at);