-- =============================================================================
-- V1__create_schema.sql
-- Pulse Pass — esquema relacional inicial
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Tabla: venues
-- -----------------------------------------------------------------------------
CREATE TABLE venues (
                            id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            code    VARCHAR(50)  NOT NULL UNIQUE,
                            name    VARCHAR(150) NOT NULL,
                            city    VARCHAR(100) NOT NULL,
                            addrees VARCHAR(150) NOT NULL,
                            capacity BIGINT NOT NULL,
                            active active BOOLEAN NOT NULL,

                    CONSTRAINT chk_capacity CHECK (capacity > 0)
);

-- -----------------------------------------------------------------------------
-- Tabla: events
-- -----------------------------------------------------------------------------

CREATE TABLE events (
                        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        event_code      VARCHAR(50)  NOT NULL UNIQUE,
                        name            VARCHAR(50)  NOT NULL,
                        description     VARCHAR(200) NOT NULL,
                        category        VARCHAR (20) NOT NULL,
                        status          VARCHAR (20) NOT NULL,
                        event_date      DATE NOT NULL,
                        minimum_age     INT,
                        streaming_url   VARCHAR(500),
                        venue_id BIGINT NOT NULL,

                        CONSTRAINT fk_event_venue
                            FOREIGN KEY (venue_id) REFERENCES venues (id),

                        CONSTRAINT chk_event_category
                            CHECK (category IN (
                                                'MUSIC',
                                                'SPORTS',
                                                'TECHNOLOGY',
                                                'EDUCATION',
                                                'CULTURE',
                                                'ENTERTAINMENT'
                                )),

                        CONSTRAINT chk_event_status
                            CHECK (status IN(
                                             'DRAFT',
                                             'PUBLISHED',
                                             'SOLD_OUT',
                                             'CANCELLED',
                                             'FINISHED'
                                ))
);

-- -----------------------------------------------------------------------------
-- Tabla: artists
-- -----------------------------------------------------------------------------
CREATE TABLE artists (
                         id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         stage_name      VARCHAR(75)  NOT NULL UNIQUE,
                         country         VARCHAR(50) NOT NULL,
                         genre           VARCHAR(50) NOT NULL,
                         active          BOOLEAN      NOT NULL DEFAULT TRUE
);

-- -----------------------------------------------------------------------------
-- Tabla asociativa: event_artists (relación N:M)
-- -----------------------------------------------------------------------------
CREATE TABLE event_artists (
                        event_id BIGINT NOT NULL,
                        artist_id  BIGINT NOT NULL,

                        PRIMARY KEY (event_id, artist_id),

                        CONSTRAINT fk_event_artist_event
                            FOREIGN KEY (event_id) REFERENCES events (id),

                        CONSTRAINT fk_event_artist_artist
                            FOREIGN KEY (artist_id) REFERENCES artists (id)
);

-- -----------------------------------------------------------------------------
-- Tabla: users
-- -----------------------------------------------------------------------------
CREATE TABLE users (
                       id   BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username     VARCHAR(100) UNIQUE NOT NULL,
                       email        VARCHAR(100) UNIQUE NOT NULL,
                       active       BOOLEAN NOT NULL

);

-- -----------------------------------------------------------------------------
-- Tabla: user_profiles
-- -----------------------------------------------------------------------------
CREATE TABLE user_profiles (
                                 id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 first_name         VARCHAR(50) NOT NULL,
                                 last_name          VARCHAR(50) NOT NULL,
                                 phone              VARCHAR(30),
                                 city               VARCHAR(50) ,
                                 birth_date
                                 user_id            BIGINT NOT NULL UNIQUE,

                                 CONSTRAINT fk_user_profile_user
                                     FOREIGN KEY (user_id) REFERENCES users (id)
);

-- -----------------------------------------------------------------------------
-- Tabla: tickets
-- -----------------------------------------------------------------------------
CREATE TABLE tickets (
                            id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            ticket_code      BIGINT UNIQUE NOT NULL,
                            type                   NOT NULL,
                            price            DECIMAL TIMESTAMP   NOT NULL,
                            status           VARCHAR(30) NOT NULL,
                            purchase_date    TEXT,
                            user_id        BIGINT NOT NULL UNIQUE;

                            CONSTRAINT fk_treatment_animal
                                FOREIGN KEY (animal_id) REFERENCES animals (id),

                            CONSTRAINT fk_treatment_specialist
                                FOREIGN KEY (specialist_id) REFERENCES specialists (id),

                            CONSTRAINT chk_treatment_type
                                CHECK (type IN (
                                                'WOUND_CARE',
                                                'HYDRATION',
                                                'MEDICATION',
                                                'SURGERY',
                                                'NUTRITION',
                                                'PHYSIOTHERAPY',
                                                'OBSERVATION'
                                    ))
);

-- =============================================================================
-- Índices para mejorar el rendimiento de las consultas
-- =============================================================================

CREATE INDEX idx_rescue_cases_center_id
    ON rescue_cases (rescue_center_id);

CREATE INDEX idx_rescue_cases_status
    ON rescue_cases (status);

CREATE INDEX idx_rescue_cases_rescue_date
    ON rescue_cases (rescue_date);

CREATE INDEX idx_treatments_animal_id
    ON treatments (animal_id);

CREATE INDEX idx_treatments_specialist_id
    ON treatments (specialist_id);

CREATE INDEX idx_treatments_performed_at
    ON treatments (performed_at);